site_name: Currciculum MMBbS


strict: false

nav:
  - Home: index.md
  - IT-Teilzeit:
    - KDM:
        - LF12:
            - LS1: 'IT-Teilzeit/KDM/LF12/LS1.md'
            - LS2: 'IT-Teilzeit/KDM/LF12/LS2.md'
    - FIAE:
        - LF1:
           - LS1: 'IT-Teilzeit/FIAE/LF1/LS1.md' 
           - LS1: 'IT-Teilzeit/FIAE/LF1/LS2.md' 
           - LS1: 'IT-Teilzeit/FIAE/LF1/LS3.md' 

