site_name: Currciculum MMBbS


strict: false


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          
          

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



nav:
  - Home: index.md
  - IT-Teilzeit:
      - KDM:
          - index: 'IT-Teilzeit/KDM/index.md'
          - LF12:
              - LS1: 'IT-Teilzeit/KDM/LF12/LS1.md'
              - LS2: 'IT-Teilzeit/KDM/LF12/LS2.md'
      - FIAE:
          - index: 'IT-Teilzeit/FIAE/index.md'
          - LF1:
              - LS1: 'IT-Teilzeit/FIAE/LF1/LS1.md'
              - LS2: 'IT-Teilzeit/FIAE/LF1/LS2.md'
              - LS3: 'IT-Teilzeit/FIAE/LF1/LS3.md'


